//go:build acceptance

package acceptance

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"sync"
	"testing"
	"time"
)

// VM wraps limactl for the one Lima instance named by Config.VM. It never
// addresses any other instance (the maintainer's Colima VM runs Lima under
// its own LIMA_HOME and is not visible here anyway).
type VM struct {
	t   testing.TB
	cfg Config
}

// NewVM returns the wrapper for cfg.VM; it does not create anything.
func NewVM(t testing.TB, cfg Config) *VM {
	return &VM{t: t, cfg: cfg}
}

// Name is the Lima instance name.
func (v *VM) Name() string { return v.cfg.VM }

// limaYAML is the instance template. It is template:ubuntu-24.04 minus that
// template's `_default/mounts` layer: the VM runs Docker as root and random
// images, and has no business reading the host's home directory; files go in
// with `limactl copy`. The port rules forward only the guest's :8080 to
// 127.0.0.1:<HostPort> and ignore every other guest port, so Traefik's :80,
// the loopback Postgres on :5432 and anything else the tests start never
// collide with ports on the maintainer's Mac. containerd is off because
// install.sh installs Docker (with its own containerd) in the guest.
func (v *VM) limaYAML() string {
	return fmt.Sprintf(`# Generated by test/acceptance (vm.go) for the self-update acceptance run.
minimumLimaVersion: 2.0.0
base:
- template:_images/ubuntu-24.04
arch: %s
cpus: 4
memory: 6GiB
disk: 30GiB
containerd:
  system: false
  user: false
portForwards:
- guestPort: 8080
  hostIP: 127.0.0.1
  hostPort: %d
- guestIP: 0.0.0.0
  proto: any
  ignore: true
- guestIP: 127.0.0.1
  proto: any
  ignore: true
`, v.cfg.LimaArch(), v.cfg.HostPort)
}

// limaInstance is the part of `limactl list --format json` the harness reads.
type limaInstance struct {
	Name   string `json:"name"`
	Status string `json:"status"`
}

// Status returns the instance's Lima status ("Running", "Stopped", ...) and
// false when it does not exist.
func (v *VM) Status(ctx context.Context) (string, bool, error) {
	out, err := v.limactl(ctx, 30*time.Second, "list", "--format", "json")
	if err != nil {
		return "", false, err
	}
	for _, line := range strings.Split(out, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "{") {
			continue
		}
		var inst limaInstance
		if err := json.Unmarshal([]byte(line), &inst); err != nil {
			return "", false, fmt.Errorf("parsing limactl list output: %w", err)
		}
		if inst.Name == v.cfg.VM {
			return inst.Status, true, nil
		}
	}
	return "", false, nil
}

// Ensure creates the instance from the generated YAML when it does not exist
// and starts it when it is not running. It is idempotent.
func (v *VM) Ensure(ctx context.Context) error {
	status, exists, err := v.Status(ctx)
	if err != nil {
		return err
	}
	if !exists {
		path := filepath.Join(v.cfg.Workdir, "lima-"+v.cfg.VM+".yaml")
		if err := os.WriteFile(path, []byte(v.limaYAML()), 0o644); err != nil {
			return fmt.Errorf("writing the Lima template: %w", err)
		}
		v.t.Logf("lima template %s:\n%s", path, v.limaYAML())
		if _, err := v.limactl(ctx, 10*time.Minute, "create", "--tty=false", "--name", v.cfg.VM, path); err != nil {
			return err
		}
		status = "Stopped"
	}
	if status != "Running" {
		if _, err := v.limactl(ctx, 30*time.Minute, "start", "--tty=false", "--timeout", "25m", v.cfg.VM); err != nil {
			return err
		}
	}
	return nil
}

// Exec runs cmd with bash as the default Lima user and returns its combined
// stdout and stderr (merged inside the guest, so limactl's own warnings on the
// host's stderr stay out of it); a non-zero exit is an error that carries the
// output.
func (v *VM) Exec(ctx context.Context, cmd string) (string, error) {
	return v.shell(ctx, false, cmd)
}

// Sudo runs cmd with bash as root and returns the combined output.
func (v *VM) Sudo(ctx context.Context, cmd string) (string, error) {
	return v.shell(ctx, true, cmd)
}

func (v *VM) shell(ctx context.Context, root bool, cmd string) (string, error) {
	args := []string{"shell", "--workdir", "/", v.cfg.VM, "--"}
	if root {
		args = append(args, "sudo")
	}
	args = append(args, "bash", "-lc", "exec 2>&1\n"+cmd)
	return v.limactl(ctx, 0, args...)
}

// CopyIn copies a host file to a guest path the default Lima user can write
// (use /tmp and move it with Sudo when root has to own it).
func (v *VM) CopyIn(ctx context.Context, local, remote string) error {
	_, err := v.limactl(ctx, 10*time.Minute, "copy", "--backend=scp", local, v.cfg.VM+":"+remote)
	return err
}

// Delete force-deletes the instance.
func (v *VM) Delete(ctx context.Context) error {
	_, exists, err := v.Status(ctx)
	if err != nil || !exists {
		return err
	}
	_, err = v.limactl(ctx, 5*time.Minute, "delete", "--force", v.cfg.VM)
	return err
}

// limactl runs limactl with args, logging the command, its duration and its
// output, and returns its stdout. limactl's stderr (its own log lines) is
// only logged and, on failure, put into the error. timeout <= 0 means only
// ctx bounds it.
func (v *VM) limactl(ctx context.Context, timeout time.Duration, args ...string) (string, error) {
	if timeout > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, timeout)
		defer cancel()
	}
	v.t.Helper()
	v.t.Logf("$ limactl %s", redact(strings.Join(quoteArgs(args), " ")))
	c := exec.CommandContext(ctx, "limactl", args...)
	var stdout, stderr bytes.Buffer
	c.Stdout = &stdout
	c.Stderr = &stderr
	start := time.Now()
	err := c.Run()
	out := stdout.String()
	v.t.Logf("  (%s, err=%v)\n%s", time.Since(start).Round(time.Millisecond), err, indent(bounded(redact(out+stderr.String()), 6000)))
	if err != nil {
		return out, fmt.Errorf("limactl %s: %w: %s", args[0], err, bounded(redact(strings.TrimSpace(out+stderr.String())), 2000))
	}
	return out, nil
}

// secretRe matches what must never reach a log or report.md: install.sh's
// one-time password line, secrets from krill.env, and a bare password read
// back by AdminPassword (see redactValue).
var secretRe = regexp.MustCompile(`(Password: +|KRILL_ADMIN_PASSWORD=|KRILL_SECRET_KEY=|KRILL_DATABASE_URL=postgres://krill:)[^\s@']+`)

// redacted holds exact secret values learned at runtime (the admin password).
var (
	redactedMu sync.Mutex
	redacted   []string
)

// redactValue masks every later occurrence of v in logs and evidence.
func redactValue(v string) {
	if v == "" {
		return
	}
	redactedMu.Lock()
	redacted = append(redacted, v)
	redactedMu.Unlock()
}

// redact masks secrets in s.
func redact(s string) string {
	s = secretRe.ReplaceAllString(s, "${1}***")
	redactedMu.Lock()
	defer redactedMu.Unlock()
	for _, v := range redacted {
		s = strings.ReplaceAll(s, v, "***")
	}
	return s
}

// quoteArgs makes a logged command line readable: arguments with spaces or
// newlines are shown quoted.
func quoteArgs(args []string) []string {
	out := make([]string, len(args))
	for i, a := range args {
		if strings.ContainsAny(a, " \n\t'\"") {
			out[i] = fmt.Sprintf("%q", a)
		} else {
			out[i] = a
		}
	}
	return out
}

func bounded(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n/2] + "\n...[truncated]...\n" + s[len(s)-n/2:]
}

func indent(s string) string {
	s = strings.TrimRight(s, "\n")
	if s == "" {
		return ""
	}
	return "    " + strings.ReplaceAll(s, "\n", "\n    ")
}

// shQuote quotes s as one POSIX shell word, for values put into VM commands.
func shQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
