package observability

import (
	"bytes"
	"log/slog"
	"net"
	"sort"
	"strconv"
	"text/template"

	"github.com/proshik/krill/internal/appmetrics"
)

// AppTarget is one metrics endpoint of one app, as the module scrapes it.
type AppTarget struct {
	OrgID, AppID, EndpointID int64
	Org, Project, Env, App   string
	Token                    string // plaintext bearer token
	Port                     int32
	Path, Job                string // Job "" → the app's name
}

// TaskNode maps one task IP of an app to the Krill name of its node.
type TaskNode struct{ IP, Node string }

const AppsModuleName = "targets" // declare "targets"; instantiated as apps.targets.default

// AppsComponentLabel names one endpoint's components inside the module; the
// Metrics tab uses it to find that endpoint in the collector's API.
func AppsComponentLabel(appID, endpointID int64) string {
	return "app_" + strconv.FormatInt(appID, 10) + "_" + strconv.FormatInt(endpointID, 10)
}

type moduleRule struct{ Regex, Replacement string }

type moduleTarget struct {
	Label   string
	DNSName string // quoted
	Port    int32
	Path    string // quoted
	JobName string // quoted
	Token   string // quoted
	Nodes   []moduleRule
	Labels  []struct{ Target, Value string } // Value quoted replacement literal
}

var appsModuleTemplate = template.Must(template.New("apps").Parse(appsModuleText))

// Scrape and poll timings are written out even where they equal Alloy's
// defaults: a scrape_timeout above scrape_interval (or a poll_timeout not
// below poll_frequency) is a load error, and a load error in this module
// takes the whole collector down on a cold start.
const appsModuleText = `// Generated by Krill (app Metrics tabs). Served at /_krill/alloy/apps.
declare "targets" {
  argument "forward_to" {}
{{- range .}}

  discovery.dns "{{.Label}}" {
    names = [{{.DNSName}}]
    type  = "A"
    port  = {{.Port}}
  }

  discovery.relabel "{{.Label}}" {
    targets = discovery.dns.{{.Label}}.targets
{{- range .Nodes}}

    rule {
      source_labels = ["__address__"]
      regex         = {{.Regex}}
      target_label  = "__tmp_krill_node"
      replacement   = {{.Replacement}}
    }
{{- end}}

    rule {
      source_labels = ["__tmp_krill_node"]
      regex         = ".+"
      action        = "keep"
    }

    rule {
      source_labels = ["__tmp_krill_node"]
      target_label  = "krill_node"
    }
{{- range .Labels}}

    rule {
      target_label = "{{.Target}}"
      replacement  = {{.Value}}
    }
{{- end}}

    rule {
      action = "labeldrop"
      regex  = "__tmp_krill_node"
    }
  }

  prometheus.scrape "{{.Label}}" {
    targets         = discovery.relabel.{{.Label}}.output
    job_name        = {{.JobName}}
    metrics_path    = {{.Path}}
    scrape_interval = "30s"
    scrape_timeout  = "10s"
    honor_labels    = false

    authorization {
      type        = "Bearer"
      credentials = {{.Token}}
    }
    forward_to = argument.forward_to.value
  }
{{- end}}
}
`

// RenderAppsModule builds the module the apps collector imports. Targets are
// rendered in (AppID, EndpointID) order and each app's task IPs in IP order,
// so the same state always renders the same bytes. A target whose text cannot
// safely go into the module is skipped with a warning: one app must not take
// every other tenant's metrics down (a module that fails to load stops the
// whole collector on its next start). A target with no known task IP renders
// with no mapping rule, so "keep" drops every address it resolves — no series
// is ever written without krill_node.
func RenderAppsModule(targets []AppTarget, nodes map[int64][]TaskNode) ([]byte, error) {
	ts := append([]AppTarget(nil), targets...)
	sort.SliceStable(ts, func(i, j int) bool {
		if ts[i].AppID != ts[j].AppID {
			return ts[i].AppID < ts[j].AppID
		}
		return ts[i].EndpointID < ts[j].EndpointID
	})
	var out []moduleTarget
	for _, t := range ts {
		m, ok := toModuleTarget(t, nodes[t.AppID])
		if !ok {
			slog.Warn("observability: an app's metrics endpoint cannot go into the collector module; skipped",
				"app_id", t.AppID, "endpoint_id", t.EndpointID)
			continue
		}
		out = append(out, m)
	}
	var buf bytes.Buffer
	if err := appsModuleTemplate.Execute(&buf, out); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func toModuleTarget(t AppTarget, tasks []TaskNode) (moduleTarget, bool) {
	path, okPath := appmetrics.NormalizePath(t.Path)
	if !okPath || path != t.Path || !appmetrics.ValidPort(int(t.Port)) || !appmetrics.ValidJob(t.Job) ||
		!safeText(t.Token) || t.Token == "" {
		return moduleTarget{}, false
	}
	for _, s := range []string{t.Org, t.Project, t.Env, t.App} {
		if !SafeNodeName(s) {
			return moduleTarget{}, false
		}
	}
	job := t.Job
	if job == "" {
		job = t.App
	}
	m := moduleTarget{
		Label:   AppsComponentLabel(t.AppID, t.EndpointID),
		DNSName: alloyString("tasks.krill-" + strconv.FormatInt(t.AppID, 10)),
		Port:    t.Port,
		Path:    alloyString(path),
		JobName: alloyString(job),
		Token:   alloyString(t.Token),
	}
	sorted := append([]TaskNode(nil), tasks...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].IP < sorted[j].IP })
	port := strconv.Itoa(int(t.Port))
	for _, n := range sorted {
		if net.ParseIP(n.IP) == nil || !safeText(n.IP) || n.Node == "" || !SafeNodeName(n.Node) {
			continue
		}
		m.Nodes = append(m.Nodes, moduleRule{
			Regex:       alloyRegexLiteral(n.IP + ":" + port),
			Replacement: alloyReplacementLiteral(n.Node),
		})
	}
	for _, l := range []struct{ Target, Value string }{
		{"krill_org", t.Org},
		{"krill_org_id", strconv.FormatInt(t.OrgID, 10)},
		{"krill_project", t.Project},
		{"krill_env", t.Env},
		{"krill_app", t.App},
		{"krill_app_id", strconv.FormatInt(t.AppID, 10)},
	} {
		m.Labels = append(m.Labels, struct{ Target, Value string }{l.Target, alloyReplacementLiteral(l.Value)})
	}
	return m, true
}
