package observability

import (
	"bytes"
	"sort"
	"strings"
	"text/template"

	"github.com/proshik/krill/internal/docker"
)

const (
	AppsServiceName      = "krill-alloy-apps"
	appsVolume           = "krill-alloy-apps-data"
	ObjectLabelAppsValue = "apps-collector"
	appsProviderFile     = "krill_apps_provider"
	AppsProviderPath     = "/_krill/alloy/apps"
	AppsMemoryLimit      = 64 << 20
	AppsNanoCPUs         = 250_000_000
)

// AppsInput is what the apps collector needs besides the settings.
type AppsInput struct {
	ProviderURL   string // http://<advertise>:<port>/_krill/alloy/apps
	ProviderToken string
	Networks      []string // every organization network (orgnet names)
	Unavailable   error    // non-nil: Krill cannot be reached by the collector (panel.Upstream failed)
}

type AppsObjects struct{ Config, MetricsSecret, ProviderSecret string }

type appsConfigData struct {
	Metrics     *pushTarget
	ProviderURL string // quoted
}

var appsConfigTemplate = template.Must(template.New("apps").Funcs(template.FuncMap{"q": alloyString}).Parse(appsConfigText))

// The module is fetched with remote.http rather than import.http: only
// remote.http reads the bearer token from a file (the provider token stays a
// Swarm secret instead of sitting in the config object), and is_secret keeps
// the module — which holds every app's scrape token — out of the agent's UI.
const appsConfigText = `// Generated by Krill (Settings → Observability). Krill replaces this file on
// every settings change; edits made here are lost.
{{- with .Metrics}}

prometheus.remote_write "default" {
  endpoint {
    url              = {{q .URL}}
    protobuf_message = "prometheus.WriteRequest"
{{- if .User}}

    basic_auth {
      username = {{q .User}}
{{- if .PasswordFile}}
      password_file = {{q .PasswordFile}}
{{- end}}
    }
{{- end}}
  }
}
{{- end}}

remote.http "apps" {
  url            = {{.ProviderURL}}
  poll_frequency = "30s"
  poll_timeout   = "10s"
  is_secret      = true

  client {
    authorization {
      type             = "Bearer"
      credentials_file = "/run/secrets/krill_apps_provider"
    }
  }
}

import.string "apps" {
  content = remote.http.apps.content
}

apps.targets "default" {
  forward_to = [prometheus.remote_write.default.receiver]
}
`

// RenderAppsConfig builds the apps collector's static configuration: where to
// write and where to fetch the scrape module. It depends on the settings and
// the provider URL only — apps and organizations never change it.
func RenderAppsConfig(s Settings, providerURL string) ([]byte, error) {
	m, err := toPushTarget(s.Metrics, metricsSecretFile)
	if err != nil {
		return nil, err
	}
	if m == nil {
		return nil, ErrNothingConfigured
	}
	if !safeText(providerURL) || providerURL == "" {
		return nil, errUnsafeText
	}
	var buf bytes.Buffer
	if err := appsConfigTemplate.Execute(&buf, appsConfigData{Metrics: m, ProviderURL: alloyString(providerURL)}); err != nil {
		return nil, err
	}
	return []byte(strings.TrimLeft(buf.String(), "\n")), nil
}

// appsObjectsOf names the collector's objects. They are the collector's own
// (a separate label value), even where the content equals the node agent's
// metrics password: each service's prune then only ever sees its own objects.
func appsObjectsOf(s Settings, cfg []byte, providerToken string) AppsObjects {
	obj := AppsObjects{
		Config:         objectName("krill-alloy-apps", cfg),
		ProviderSecret: objectName("krill-alloy-apps-provider", []byte(providerToken)),
	}
	if s.Metrics.User != "" && s.Metrics.Password != "" {
		obj.MetricsSecret = objectName("krill-alloy-apps-metrics-password", []byte(s.Metrics.Password))
	}
	return obj
}

// AppsSpec is the apps collector: one task on a manager, in every
// organization's network so it can reach tasks.krill-<id> there. Unlike the
// node agent it holds no docker socket and mounts nothing from the host — a
// container that sits in tenant networks must not be able to reach the
// engine. It listens on nothing reachable (UI on loopback).
func AppsSpec(obj AppsObjects, baseNetwork string, orgNetworks []string) docker.ServiceSpec {
	orgs := append([]string(nil), orgNetworks...)
	sort.Strings(orgs)
	spec := docker.ServiceSpec{
		Name:        AppsServiceName,
		Image:       Image,
		Args:        nodeArgs(),
		Replicas:    1,
		Networks:    append([]string{baseNetwork}, orgs...),
		Constraints: []string{"node.role==manager"},
		Mounts:      []docker.MountSpec{{Type: "volume", Source: appsVolume, Target: storagePath}},
		Configs:     []docker.FileRef{{Name: obj.Config, Target: configPath}},
		Secrets: []docker.FileRef{
			{Name: obj.ProviderSecret, Target: appsProviderFile, Mode: 0o400},
		},
		MemoryLimitBytes: AppsMemoryLimit,
		NanoCPUs:         AppsNanoCPUs,
		UpdateStopFirst:  true, // one WAL directory
	}
	if obj.MetricsSecret != "" {
		spec.Secrets = append(spec.Secrets, docker.FileRef{Name: obj.MetricsSecret, Target: metricsSecretFile, Mode: 0o400})
	}
	spec.Labels = map[string]string{specHashLabel: fingerprint(spec)}
	return spec
}
