package observability

import (
	"bytes"
	"errors"
	"log/slog"
	"regexp"
	"sort"
	"strings"
	"text/template"
	"unicode"
)

const (
	configPath        = "/etc/alloy/config.alloy"
	storagePath       = "/var/lib/alloy/data"
	secretsDir        = "/run/secrets/"
	metricsSecretFile = "krill_metrics_password"
	logsSecretFile    = "krill_logs_password"
)

var errUnsafeText = errors.New("observability: a setting contains characters that cannot go into the agent configuration")

type pushTarget struct {
	URL          string
	User         string
	PasswordFile string // "" when there is no password
}

// NodeName maps a Swarm node's hostname to the name Krill shows for it — the
// same node_labels.label the Nodes page, Topology and the app page already
// show, resolved fresh from the cluster on every reconcile pass (see
// obsNodeNames in cmd/krill/main.go). Name is "" for a node with no label:
// RenderNodeConfig leaves it out of the krill_node mapping (it keeps showing
// its raw Swarm hostname), but Reconcile still counts it — labelled or not —
// for node coverage (see Expected).
//
// Expected reports whether Reconcile should still expect a container on this
// node this pass: Availability != "drain" (docker.SwarmNode.Availability). A
// DOWN or paused node is still expected — Swarm leaves whatever container it
// last placed there running; only draining actively removes it. State is
// deliberately not part of this: a down node is exactly the case Coverage
// exists to catch (its container is alive and still on the PREVIOUS
// configuration) — excluding it here would silence the one finding this
// whole mechanism was built to surface. See Coverage in reconcile.go.
type NodeName struct {
	Hostname, Name string
	Expected       bool
}

// DisplayName is the name Krill shows for this node: its Krill name when one
// is set, its raw Swarm hostname otherwise.
func (n NodeName) DisplayName() string {
	if n.Name != "" {
		return n.Name
	}
	return n.Hostname
}

// nodeRelabelRule is one NodeName rendered into the two Alloy string literals
// a relabel rule needs: both already quoted, so the template embeds them
// as-is.
type nodeRelabelRule struct {
	Regex       string // hostname, regex-escaped and quoted
	Replacement string // the Krill name, quoted
}

type nodeConfigData struct {
	Metrics   *pushTarget
	Logs      *pushTarget
	LogLabels []struct{ Meta, Target string }
	Nodes     []nodeRelabelRule
}

// alloyString quotes s as an Alloy string literal. RenderNodeConfig refuses
// text with quotes, backslashes or control characters first, so quoting is
// all that is left to do.
func alloyString(s string) string { return `"` + s + `"` }

var nodeTemplate = template.Must(template.New("node").Funcs(template.FuncMap{"q": alloyString}).Parse(nodeConfigText))

const nodeConfigText = `// Generated by Krill (Settings → Observability). Krill replaces this file on
// every settings change; edits made here are lost.
{{- with .Metrics}}

prometheus.exporter.unix "host" {
  procfs_path    = "/host/proc"
  sysfs_path     = "/host/sys"
  rootfs_path    = "/host/root"
  udev_data_path = "/host/root/run/udev/data"
}

prometheus.scrape "host" {
  targets         = prometheus.exporter.unix.host.targets
  scrape_interval = "30s"
  forward_to      = [prometheus.relabel.node.receiver]
}

prometheus.relabel "node" {
  rule {
    target_label = "krill_node"
    replacement  = constants.hostname
  }
{{- if $.Nodes}}

  rule {
    target_label = "__tmp_krill_node"
    replacement  = constants.hostname
  }
{{- range $.Nodes}}

  rule {
    source_labels = ["__tmp_krill_node"]
    regex         = {{.Regex}}
    target_label  = "krill_node"
    replacement   = {{.Replacement}}
  }
{{- end}}

  rule {
    action = "labeldrop"
    regex  = "__tmp_krill_node"
  }
{{- end}}
  forward_to = [prometheus.remote_write.default.receiver]
}

prometheus.remote_write "default" {
  endpoint {
    url              = {{q .URL}}
    protobuf_message = "prometheus.WriteRequest"
{{- if .User}}

    basic_auth {
      username = {{q .User}}
{{- if .PasswordFile}}
      password_file = {{q .PasswordFile}}
{{- end}}
    }
{{- end}}
  }
}
{{- end}}
{{- with .Logs}}

discovery.docker "node" {
  host             = "unix:///var/run/docker.sock"
  refresh_interval = "15s"
}

discovery.relabel "containers" {
  targets = []
{{- range $.LogLabels}}

  rule {
    source_labels = [{{q .Meta}}]
    target_label  = {{q .Target}}
  }
{{- end}}
}

loki.source.docker "node" {
  host          = "unix:///var/run/docker.sock"
  targets       = discovery.docker.node.targets
  relabel_rules = discovery.relabel.containers.rules
  labels        = {krill_node = constants.hostname}
  forward_to    = [{{if $.Nodes}}loki.relabel.node.receiver{{else}}loki.write.default.receiver{{end}}]
}
{{- if $.Nodes}}

loki.relabel "node" {
  forward_to = [loki.write.default.receiver]

  rule {
    target_label = "__tmp_krill_node"
    replacement  = constants.hostname
  }
{{- range $.Nodes}}

  rule {
    source_labels = ["__tmp_krill_node"]
    regex         = {{.Regex}}
    target_label  = "krill_node"
    replacement   = {{.Replacement}}
  }
{{- end}}

  rule {
    action = "labeldrop"
    regex  = "__tmp_krill_node"
  }
}
{{- end}}

loki.write "default" {
  endpoint {
    url = {{q .URL}}
{{- if .User}}

    basic_auth {
      username = {{q .User}}
{{- if .PasswordFile}}
      password_file = {{q .PasswordFile}}
{{- end}}
    }
{{- end}}
  }
}
{{- end}}
`

// alloyRegexLiteral quotes hostname as an Alloy string literal holding a
// regex that matches it exactly. regexp.QuoteMeta escapes the regex
// metacharacters; the extra backslash doubling is Alloy's own string-escape
// rule, not the regex syntax — confirmed against the pinned agent image
// (grafana/alloy:v1.19.2): a lone "\." in an Alloy string is rejected at load
// with "unknown escape sequence", even though `alloy validate` accepts it
// (see internal/observability/config_integration_test.go). Safe only because
// callers must have validated hostname with safeText first (see nodeRules).
func alloyRegexLiteral(hostname string) string {
	return alloyString(strings.ReplaceAll(regexp.QuoteMeta(hostname), `\`, `\\`))
}

// SafeNodeName reports whether name can go into the agent configuration as a
// node's display name. Unlike safeText (written for URLs and logins, which
// also rejects whitespace because those are meant to be single tokens), a
// node's name only needs to avoid breaking out of a double-quoted Alloy
// string or introducing a stray control character into the generated file: a
// quote, a backslash, or a control character (including a newline). Spaces,
// Cyrillic, dots and hyphens are all a normal, harmless part of a name
// inside an Alloy string literal, and node_labels.label already allows them
// — setNodeLabel (internal/server/node_handlers.go) rejects a new label with
// this same function so the operator finds out at save time, not from a
// warning log the next time the agent reconciles; a label saved before that
// check existed is still caught here.
func SafeNodeName(name string) bool {
	for _, r := range name {
		if unicode.IsControl(r) || r == '"' || r == '\\' {
			return false
		}
	}
	return true
}

// alloyReplacementLiteral quotes name as an Alloy string literal safe to use
// as a relabel rule's replacement. A relabel replacement is always expanded
// via regexp's ExpandString (so "$1", "$name", etc. substitute capture
// groups — this happens even though our regex has none), so a literal "$" in
// the node's name must be doubled to "$$" or it is silently consumed as a
// backreference: a name of "a$1" would otherwise render as just "a", since
// capture group 1 doesn't exist and expands to "". Safe only because callers
// must have validated name with SafeNodeName first (see nodeRules).
func alloyReplacementLiteral(name string) string {
	return alloyString(strings.ReplaceAll(name, "$", "$$"))
}

// nodeRules turns Krill's node name mapping into the per-node relabel rules
// appended after the metrics/logs "krill_node = constants.hostname" rule (see
// the template's "__tmp_krill_node" rule: every per-node rule below matches
// against that immutable snapshot of the raw hostname, not against
// "krill_node" itself — matching against "krill_node" would let one node's
// rule see another's already-rewritten value when a node's chosen Name
// happens to equal another node's raw hostname, silently relabeling the
// wrong node). Entries with an empty Hostname or Name are skipped — an
// unmapped node keeps its raw hostname rather than get a bogus rule.
//
// node_labels.label is close to free text (setNodeLabel only rejects a
// quote, backslash or control character — see SafeNodeName — and an
// over-length value; existing rows predate even that), so an entry whose
// Name fails SafeNodeName, or whose Hostname fails the stricter safeText
// (Swarm hostnames are trusted DNS-like strings; this should not trigger in
// practice), is skipped with a warning rather than failing the whole render:
// one badly-named node must not freeze the entire agent on a stale config or
// leave it undeployed, and RenderNodeConfig has no way to report "which
// node" through an error that ends up as the observability page's unrelated
// settings-validation LastErr anyway.
//
// Sorting by Hostname (with Name as a tiebreak, for the pathological case of
// two entries sharing a Hostname) keeps the rendered config, and so the
// object hash and the deploy it triggers, stable regardless of the order the
// caller happened to resolve nodes in.
func nodeRules(nodes []NodeName) []nodeRelabelRule {
	kept := make([]NodeName, 0, len(nodes))
	for _, n := range nodes {
		if n.Hostname == "" || n.Name == "" {
			continue
		}
		if !safeText(n.Hostname) || !SafeNodeName(n.Name) {
			slog.Warn("observability: a node's name cannot go into the agent configuration; it keeps its raw hostname label",
				"name", n.Name, "hostname", n.Hostname)
			continue
		}
		kept = append(kept, n)
	}
	sort.SliceStable(kept, func(i, j int) bool {
		if kept[i].Hostname != kept[j].Hostname {
			return kept[i].Hostname < kept[j].Hostname
		}
		return kept[i].Name < kept[j].Name
	})
	rules := make([]nodeRelabelRule, len(kept))
	for i, n := range kept {
		rules[i] = nodeRelabelRule{Regex: alloyRegexLiteral(n.Hostname), Replacement: alloyReplacementLiteral(n.Name)}
	}
	return rules
}

func toPushTarget(t Target, secretFile string) (*pushTarget, error) {
	if !t.Configured() {
		return nil, nil
	}
	if !safeText(t.URL) || !safeText(t.User) {
		return nil, errUnsafeText
	}
	p := &pushTarget{URL: t.URL, User: t.User}
	if t.User != "" && t.Password != "" {
		p.PasswordFile = secretsDir + secretFile
	}
	return p, nil
}

// nodeArgs is the agent's command line: the UI stays on loopback, so nothing
// on any overlay network can reach it.
func nodeArgs() []string {
	return []string{"run", "--server.http.listen-addr=127.0.0.1:12345", "--storage.path=" + storagePath, configPath}
}

// RenderNodeConfig builds the node agent's configuration. Passwords are not
// in it: the agent reads them from the Swarm secrets NodeSpec mounts. nodes
// maps Swarm hostnames to the names Krill shows for them (empty/nil renders
// the plain "krill_node = constants.hostname" label, as before this mapping
// existed).
func RenderNodeConfig(s Settings, nodes []NodeName) ([]byte, error) {
	m, err := toPushTarget(s.Metrics, metricsSecretFile)
	if err != nil {
		return nil, err
	}
	l, err := toPushTarget(s.Logs, logsSecretFile)
	if err != nil {
		return nil, err
	}
	if m == nil && l == nil {
		return nil, ErrNothingConfigured
	}
	rules := nodeRules(nodes)
	var buf bytes.Buffer
	if err := nodeTemplate.Execute(&buf, nodeConfigData{Metrics: m, Logs: l, LogLabels: logLabels, Nodes: rules}); err != nil {
		return nil, err
	}
	return []byte(strings.TrimLeft(buf.String(), "\n")), nil
}
