package observability

import (
	"bytes"
	"errors"
	"strings"
	"text/template"
)

const (
	configPath        = "/etc/alloy/config.alloy"
	storagePath       = "/var/lib/alloy/data"
	secretsDir        = "/run/secrets/"
	metricsSecretFile = "krill_metrics_password"
	logsSecretFile    = "krill_logs_password"
)

var errUnsafeText = errors.New("observability: a setting contains characters that cannot go into the agent configuration")

type pushTarget struct {
	URL          string
	User         string
	PasswordFile string // "" when there is no password
}

type nodeConfigData struct {
	Metrics   *pushTarget
	Logs      *pushTarget
	LogLabels []struct{ Meta, Target string }
}

// alloyString quotes s as an Alloy string literal. RenderNodeConfig refuses
// text with quotes, backslashes or control characters first, so quoting is
// all that is left to do.
func alloyString(s string) string { return `"` + s + `"` }

var nodeTemplate = template.Must(template.New("node").Funcs(template.FuncMap{"q": alloyString}).Parse(nodeConfigText))

const nodeConfigText = `// Generated by Krill (Settings → Observability). Krill replaces this file on
// every settings change; edits made here are lost.
{{- with .Metrics}}

prometheus.exporter.unix "host" {
  procfs_path    = "/host/proc"
  sysfs_path     = "/host/sys"
  rootfs_path    = "/host/root"
  udev_data_path = "/host/root/run/udev/data"
}

prometheus.scrape "host" {
  targets         = prometheus.exporter.unix.host.targets
  scrape_interval = "30s"
  forward_to      = [prometheus.relabel.node.receiver]
}

prometheus.relabel "node" {
  rule {
    target_label = "krill_node"
    replacement  = constants.hostname
  }
  forward_to = [prometheus.remote_write.default.receiver]
}

prometheus.remote_write "default" {
  endpoint {
    url              = {{q .URL}}
    protobuf_message = "prometheus.WriteRequest"
{{- if .User}}

    basic_auth {
      username = {{q .User}}
{{- if .PasswordFile}}
      password_file = {{q .PasswordFile}}
{{- end}}
    }
{{- end}}
  }
}
{{- end}}
{{- with .Logs}}

discovery.docker "node" {
  host             = "unix:///var/run/docker.sock"
  refresh_interval = "15s"
}

discovery.relabel "containers" {
  targets = []
{{- range $.LogLabels}}

  rule {
    source_labels = [{{q .Meta}}]
    target_label  = {{q .Target}}
  }
{{- end}}
}

loki.source.docker "node" {
  host          = "unix:///var/run/docker.sock"
  targets       = discovery.docker.node.targets
  relabel_rules = discovery.relabel.containers.rules
  labels        = {krill_node = constants.hostname}
  forward_to    = [loki.write.default.receiver]
}

loki.write "default" {
  endpoint {
    url = {{q .URL}}
{{- if .User}}

    basic_auth {
      username = {{q .User}}
{{- if .PasswordFile}}
      password_file = {{q .PasswordFile}}
{{- end}}
    }
{{- end}}
  }
}
{{- end}}
`

func toPushTarget(t Target, secretFile string) (*pushTarget, error) {
	if !t.Configured() {
		return nil, nil
	}
	if !safeText(t.URL) || !safeText(t.User) {
		return nil, errUnsafeText
	}
	p := &pushTarget{URL: t.URL, User: t.User}
	if t.User != "" && t.Password != "" {
		p.PasswordFile = secretsDir + secretFile
	}
	return p, nil
}

// nodeArgs is the agent's command line: the UI stays on loopback, so nothing
// on any overlay network can reach it.
func nodeArgs() []string {
	return []string{"run", "--server.http.listen-addr=127.0.0.1:12345", "--storage.path=" + storagePath, configPath}
}

// RenderNodeConfig builds the node agent's configuration. Passwords are not
// in it: the agent reads them from the Swarm secrets NodeSpec mounts.
func RenderNodeConfig(s Settings) ([]byte, error) {
	m, err := toPushTarget(s.Metrics, metricsSecretFile)
	if err != nil {
		return nil, err
	}
	l, err := toPushTarget(s.Logs, logsSecretFile)
	if err != nil {
		return nil, err
	}
	if m == nil && l == nil {
		return nil, ErrNothingConfigured
	}
	var buf bytes.Buffer
	if err := nodeTemplate.Execute(&buf, nodeConfigData{Metrics: m, Logs: l, LogLabels: logLabels}); err != nil {
		return nil, err
	}
	return []byte(strings.TrimLeft(buf.String(), "\n")), nil
}
